#!/bin/bash
# Debian Package Builder for adaptive-brightness-linux
# Generated by Antigravity for LeanBitLab

set -e

echo "Starting Debian Package Builder..."

# Define directories
STAGE_DIR="dist/deb_build"
DEBIAN_DIR="$STAGE_DIR/DEBIAN"
BIN_DIR="$STAGE_DIR/usr/bin"
APP_DIR="$STAGE_DIR/usr/share/applications"
SYSTEMD_DIR="$STAGE_DIR/usr/lib/systemd/user"

# Clean previous build artifacts
rm -rf dist/
mkdir -p "$DEBIAN_DIR"
mkdir -p "$BIN_DIR"
mkdir -p "$APP_DIR"
mkdir -p "$SYSTEMD_DIR"

echo "Copying scripts and applications..."
# Core Python Daemon
cp auto-brightness-daemon.py "$BIN_DIR/"
chmod 755 "$BIN_DIR/auto-brightness-daemon.py"

# PySide6 GUI control panel
cp gui.py "$BIN_DIR/auto-brightness-gui"
chmod 755 "$BIN_DIR/auto-brightness-gui"

# Desktop Entry
cp auto-brightness-gui.desktop "$APP_DIR/"
chmod 644 "$APP_DIR/auto-brightness-gui.desktop"

# Systemd User Service (Modified ExecStart for global /usr/bin installation)
sed 's|%h/.local/bin/auto-brightness-daemon.py|/usr/bin/auto-brightness-daemon.py|g' auto-brightness.service > "$SYSTEMD_DIR/auto-brightness.service"
chmod 644 "$SYSTEMD_DIR/auto-brightness.service"

echo "Generating package metadata..."
# Create DEBIAN/control
cat << 'EOF' > "$DEBIAN_DIR/control"
Package: adaptive-brightness-linux
Version: 1.0.1
Section: utils
Priority: optional
Architecture: all
Maintainer: LeanBitLab <leanbitlab@users.noreply.github.com>
Depends: brightnessctl, python3, systemd
Recommends: python3-pyside6, libnotify-bin
Description: Adaptive screen brightness with machine learning.
 A beautiful, minimalist monochrome desktop control panel GUI,
 real-time visual spline curves, pause timers, logs, and background timers.
EOF

# Create DEBIAN/postinst
cat << 'EOF' > "$DEBIAN_DIR/postinst"
#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    echo "Reloading systemd user daemon..."
    systemctl --global daemon-reload || true
fi
EOF
chmod 755 "$DEBIAN_DIR/postinst"

# Create DEBIAN/prerm
cat << 'EOF' > "$DEBIAN_DIR/prerm"
#!/bin/bash
set -e

# Disable service globally before removing
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    echo "Disabling adaptive brightness services globally..."
    systemctl --global disable auto-brightness.service || true
fi
EOF
chmod 755 "$DEBIAN_DIR/prerm"

# Build the Debian package
echo "Compiling deb package..."
dpkg-deb --root-owner-group --build "$STAGE_DIR" adaptive-brightness_1.0.1_all.deb

echo "Debian package successfully built: adaptive-brightness_1.0.1_all.deb"
